### Obtener todos los ítems
GET http://localhost:3000/api/items

### Crear un ítem
# @name createItem
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "name": "Lightsaber",
    "description": "A gentleman's weapon"
}

###ID
@id = {{createItem.response.body.data.id}}

### Obtener un ítem
GET http://localhost:3000/api/items/{{id}}

### Actualizar un ítem
PUT http://localhost:3000/api/items/{{id}}
Content-Type: application/json

{
    "name": "Lightsaber",
    "description": "A weapon for a more civilized age"
}

### Crear otro ítem
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "name": "Death Star",
    "description": "Planet killer"
}

### Crear ítem para eliminar
# @name createItemToDelete
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "name": "Blaster",
    "description": "A weapon for a less civilized age"
}

### Eliminar un ítem
@idToDelete = {{createItemToDelete.response.body.data.id}}

DELETE http://localhost:3000/api/items/{{idToDelete}}



