### Obtener todas las clases
GET http://localhost:3000/api/characters/classes

### Crear una clase
# @name createCharacterClass
POST http://localhost:3000/api/characters/classes
Content-Type: application/json

{
    "name": "Lord Sith",
    "description": "A wielder of the force who has embraced the dark side"
}

### ID
@id = {{createCharacterClass.response.body.data.id}}

### Obtener una clase
GET http://localhost:3000/api/characters/classes/{{id}}


### Actualizar una clase
PUT  http://localhost:3000/api/characters/classes/{{id}}
Content-Type: application/json

{
    "name": "Lord Sith",
    "description": "Wielder of the force who has embraced the dark side"
}

### Crear otra clase
POST http://localhost:3000/api/characters/classes
Content-Type: application/json

{
    "name": "Jedi Knight",
    "description": "Warrior who has dedicated their life to the force and the Jedi order."
}

### Crear una tercera clase
POST http://localhost:3000/api/characters/classes
Content-Type: application/json

{
    "name": "Fallen Jedi",
    "description": "A righteous warrior who has fallen to the dark side of the force by embracing their emotions and passions in order to gain power."
}

### Crear clase para eliminar
# @name createCharacterClassToDelete
POST http://localhost:3000/api/characters/classes
Content-Type: application/json

{
    "name": "Fallen Jedi",
    "description": "A righteous warrior who has fallen to the dark side of the force by embracing their emotions and passions in order to gain power."
}

### Eliminar una clase
@idToDelete = {{createCharacterClassToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/characters/classes/{{idToDelete}}